<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated;

use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\ProductVariation;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\ExternalProduct;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\VariableProduct;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\SimpleProduct;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\Coupon;

class TypeRegistry {
	/**
	 * Return all concrete types that implement interfaces.
	 *
	 * Pass this to the Schema 'types' config so that inline fragments
	 * (e.g. `... on VariableProduct`) are resolvable.
	 *
	 * @return array
	 */
	public static function get_interface_implementors(): array {
		return array(
			ProductVariation::get(),
			ExternalProduct::get(),
			VariableProduct::get(),
			SimpleProduct::get(),
			Coupon::get(),
		);
	}
}
