# See https://github.com/shufo/auto-assign-reviewer-by-files/blob/main/README.md for configuration format

"*":
  - Flux

".github/**/*":
  - Flux

"bin/*":
  - Flux

"docs/**/*":
  - Developer Advocacy

"packages/js/api/**/*":
  - Flux

"packages/js/components/**/*":
  - Kirigami

"packages/js/csv-export/**/*":
  - SomewhereWarm

"packages/js/currency/**/*":
  - Rubik

"packages/js/customer-effort-score/**/*":
  - Kirigami

"packages/js/data/**/*":
  - Ventures

"packages/js/date/**/*":
  - Rubik

"packages/js/dependency-extraction-webpack-plugin/**/*":
  - Flux

"packages/js/eslint-plugin/**/*":
  - Flux

"packages/js/experimental/**/*":
  - Kirigami

"packages/js/explat/**/*":
  - Kirigami

"packages/js/navigation/**/*":
  - SomewhereWarm

"packages/js/number/**/*":
  - Rubik

"packages/js/onboarding/**/*":
  - Rubik

"packages/js/product-editor/**/*":
  - Kirigami

"packages/js/tracks/**/*":
  - Flux

"plugins/poocommerce/**/*":
  - Flux

"plugins/poocommerce/templates/**/*":
  - Rubik
  - Kirigami

"plugins/poocommerce/templates/emails/**/*":
  - Ballade

"plugins/poocommerce/src/Admin/**/*":
  - team: Kirigami

"plugins/poocommerce/src/Blocks/**/*":
  - Rubik
  - Kirigami

"plugins/poocommerce/src/Internal/Admin/**/*":
  - Kirigami

"plugins/poocommerce/src/StoreApi/**/*":
  - Rubik
  - Kirigami

"plugins/poocommerce/client/admin/**/*":
  - Kirigami

"plugins/poocommerce/client/blocks/**/*":
  - Rubik
  - Kirigami

"plugins/poocommerce-beta-tester/**/*":
  - Flux

"tools/**/*":
  - Flux

'**/composer.json':
  - Flux

'**/package.json':
  - Flux
