'package: @poocommerce/e2e-utils-playwright':
  - packages/js/e2e-utils-playwright/**/*

'package: @poocommerce/components':
  - packages/js/components/**/*

'package: @poocommerce/csv-export':
  - packages/js/csv-export/**/*

'package: @poocommerce/currency':
  - packages/js/currency/**/*

'package: @poocommerce/customer-effort-score':
  - packages/js/customer-effort-score/**/*

'package: @poocommerce/data':
  - packages/js/data/**/*

'package: @poocommerce/date':
  - packages/js/date/**/*

'package: dependency-extraction-webpack-plugin':
  - packages/js/dependency-extraction-webpack-plugin/**/*

'package: @poocommerce/eslint-plugin':
  - packages/js/eslint-plugin/**/*

'package: @poocommerce/experimental':
  - packages/js/experimental/**/*

'package: @poocommerce/explat':
  - packages/js/explat/**/*

'package: @poocommerce/navigation':
  - packages/js/navigation/**/*

'package: @poocommerce/number':
  - packages/js/number/**/*

'package: @poocommerce/onboarding':
  - packages/js/onboarding/**/*

'package: @poocommerce/tracks':
  - packages/js/tracks/**/*

'plugin: poocommerce':
  - plugins/poocommerce/**/*

'plugin: poocommerce beta tester':
  - plugins/poocommerce-beta-tester/**/*

'focus: performance tests':
  - plugins/poocommerce/tests/performance/**/*
  - plugins/poocommerce/tests/metrics/**/*

'focus: api tests':
  - plugins/poocommerce/tests/e2e-pw/tests/api-tests/**/*

'focus: e2e tests':
  - plugins/poocommerce/tests/e2e-pw/**/*
  - plugins/poocommerce/client/blocks/tests/e2e/**/*

'Documentation':
  - docs/**/*

'focus: monorepo infrastructure':
  - .github/**/*
  - bin/**/*
  - tools/**/*
  - '**/composer.json'
  - '**/package.json'
