'package: @poocommerce/e2e-utils-playwright':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/e2e-utils-playwright/**/*

'package: @poocommerce/components':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/components/**/*

'package: @poocommerce/csv-export':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/csv-export/**/*

'package: @poocommerce/currency':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/currency/**/*

'package: @poocommerce/customer-effort-score':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/customer-effort-score/**/*

'package: @poocommerce/data':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/data/**/*

'package: @poocommerce/date':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/date/**/*

'package: dependency-extraction-webpack-plugin':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/dependency-extraction-webpack-plugin/**/*

'package: @poocommerce/eslint-plugin':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/eslint-plugin/**/*

'package: @poocommerce/experimental':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/experimental/**/*

'package: @poocommerce/explat':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/explat/**/*

'package: @poocommerce/navigation':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/navigation/**/*

'package: @poocommerce/number':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/number/**/*

'package: @poocommerce/onboarding':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/onboarding/**/*

'package: @poocommerce/tracks':
  - changed-files:
      - any-glob-to-any-file:
          - packages/js/tracks/**/*

'plugin: poocommerce':
  - changed-files:
      - any-glob-to-any-file:
          - plugins/poocommerce/**/*

'plugin: poocommerce beta tester':
  - changed-files:
      - any-glob-to-any-file:
          - plugins/poocommerce-beta-tester/**/*

'focus: performance tests':
  - changed-files:
      - any-glob-to-any-file:
          - plugins/poocommerce/tests/performance/**/*
          - plugins/poocommerce/tests/metrics/**/*

'focus: api tests':
  - changed-files:
      - any-glob-to-any-file:
          - plugins/poocommerce/tests/e2e/tests/api-tests/**/*

'focus: e2e tests':
  - changed-files:
      - any-glob-to-any-file:
          - plugins/poocommerce/tests/e2e/**/*

'Documentation':
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*

'focus: monorepo infrastructure':
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - bin/**/*
          - tools/**/*
          - '**/composer.json'
          - '**/package.json'
