packages:
    - 'packages/js/*'
    - 'packages/php/*'
    - 'plugins/*'
    - 'plugins/poocommerce/client/admin'
    - 'plugins/poocommerce/client/blocks'
    - 'plugins/poocommerce/client/legacy'
    - 'plugins/poocommerce/client/blocks/bin/eslint-plugin-poocommerce'
    - 'tools/monorepo-merge'
    - 'tools/code-analyzer'
    - 'tools/compare-perf'
    - 'tools/package-release'
    - 'tools/cherry-pick'
    - 'tools/release-posts'
    - 'tools/storybook'
    - 'tools/monorepo-utils'
