<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums;

use Automattic\PooCommerce\Api\Enums\Products\ProductType as ProductTypeEnum;
use Automattic\PooCommerce\Api\Infrastructure\Schema\EnumType;

class ProductType {
	private static ?EnumType $instance = null;

	public static function get(): EnumType {
		if ( null === self::$instance ) {
			self::$instance = new EnumType(
				array(
					'name'        => 'ProductType',
					'description' => __( 'The type of a PooCommerce product.', 'poocommerce' ),
					'values'      => array(
						'SIMPLE'    => array(
							'value'       => ProductTypeEnum::Simple,
							'description' => __( 'A simple product.', 'poocommerce' ),
						),
						'GROUPED'   => array(
							'value'       => ProductTypeEnum::Grouped,
							'description' => __( 'A grouped product.', 'poocommerce' ),
						),
						'EXTERNAL'  => array(
							'value'       => ProductTypeEnum::External,
							'description' => __( 'An external/affiliate product.', 'poocommerce' ),
						),
						'VARIABLE'  => array(
							'value'       => ProductTypeEnum::Variable,
							'description' => __( 'A variable product with variations.', 'poocommerce' ),
						),
						'VARIATION' => array(
							'value'       => ProductTypeEnum::Variation,
							'description' => __( 'A product variation.', 'poocommerce' ),
						),
						'OTHER'     => array(
							'value'       => ProductTypeEnum::Other,
							'description' => __( 'The product type is not one of the standard PooCommerce values (e.g. added by a plugin). Inspect raw_product_type for the underlying value.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
