<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Inheritance\OverriddenCapQuery as OverriddenCapQueryCommand;
use Automattic\PooCommerce\Api\Infrastructure\QueryInfoExtractor;
use Automattic\PooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ResolveInfo;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class OverriddenCapQuery {
	public static function get_field_definition(): array {
		return array(
			'type'          => Type::nonNull(
				new \Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType(
					array(
						'name'   => 'OverriddenCapQueryResult',
						'fields' => array(
							'result' => array( 'type' => Type::nonNull( Type::string() ) ),
						),
					)
				)
			),
			'description'   => __( 'Overrides the inherited manage_options with manage_categories', 'poocommerce' ),
			'authorization' => array(
				array(
					'attribute' => 'RequiredCapability',
					'args'      => array(
						0 => 'manage_categories',
					),
				),
			),
			'args'          => array(),
			'resolve'       => array( self::class, 'resolve' ),
		);
	}

	public static function resolve( mixed $root, array $args, mixed $context, ResolveInfo $info ): mixed {
		// Standalone authorization gate: no authorize() method on the command,
		// so the autodiscovered authorization attributes are the sole guard.
		if ( ! self::compute_preauthorized( $context['principal'] ) ) {
			throw ResolverHelpers::build_authorization_error( $context['principal'] );
		}

		// Publish the root query's metadata so downstream field-level
		// authorization gates can read it via `$_metadata['query']`.
		// $context is an ArrayObject (see GraphQLController::process_request())
		// so the mutation propagates to nested resolvers.
		$context['_query_metadata'] = array();

		$command = \Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Infrastructure\ClassResolver::resolve_class( OverriddenCapQueryCommand::class );

		$execute_args = array();

		$result = ResolverHelpers::execute_command( $command, $execute_args );

		return array( 'result' => $result );
	}

	/**
	 * Compute the value `_preauthorized` would carry for a given principal —
	 * the AND of the autodiscovered authorization attributes' authorize()
	 * outcomes on this command. Single source of truth for both the resolver's
	 * own gates and external (code-API) callers asking about authorization
	 * without going through GraphQL execution.
	 *
	 * Returns true vacuously when the command has no authorization attributes
	 * (in that case authorize() on the command is the sole guard, and that
	 * method should be consulted instead).
	 */
	public static function compute_preauthorized( \Automattic\PooCommerce\Api\Infrastructure\Principal $principal ): bool {
		return ( new \Automattic\PooCommerce\Api\Attributes\RequiredCapability( 'manage_categories' ) )->authorize( $principal );
	}
}
