<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLQueries;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Queries\Authorization\PublicWidgetAccess as PublicWidgetAccessCommand;
use Automattic\PooCommerce\Api\Infrastructure\QueryInfoExtractor;
use Automattic\PooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\Widget as WidgetType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ResolveInfo;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class PublicWidgetAccess {
	public static function get_field_definition(): array {
		return array(
			'type'          => WidgetType::get(),
			'description'   => __( 'Fetch a widget without query-level gating; field-level gates apply.', 'poocommerce' ),
			'authorization' => array(
				array(
					'attribute' => 'PublicAccess',
					'args'      => array(),
				),
			),
			'args'          => array(),
			'resolve'       => array( self::class, 'resolve' ),
		);
	}

	public static function resolve( mixed $root, array $args, mixed $context, ResolveInfo $info ): mixed {
		// Publish the root query's metadata so downstream field-level
		// authorization gates can read it via `$_metadata['query']`.
		// $context is an ArrayObject (see GraphQLController::process_request())
		// so the mutation propagates to nested resolvers.
		$context['_query_metadata'] = array();

		$command = \Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Infrastructure\ClassResolver::resolve_class( PublicWidgetAccessCommand::class );

		$execute_args = array();

		$result = ResolverHelpers::execute_command( $command, $execute_args );

		return $result;
	}

	/**
	 * Compute the value `_preauthorized` would carry for a given principal —
	 * the AND of the autodiscovered authorization attributes' authorize()
	 * outcomes on this command. Single source of truth for both the resolver's
	 * own gates and external (code-API) callers asking about authorization
	 * without going through GraphQL execution.
	 *
	 * Returns true vacuously when the command has no authorization attributes
	 * (in that case authorize() on the command is the sole guard, and that
	 * method should be consulted instead).
	 */
	public static function compute_preauthorized( \Automattic\PooCommerce\Api\Infrastructure\Principal $principal ): bool {
		return true;
	}
}
