<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Enums;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Enums\Color as ColorEnum;
use Automattic\PooCommerce\Api\Infrastructure\Schema\EnumType;

class Color {
	private static ?EnumType $instance = null;

	public static function get(): EnumType {
		if ( null === self::$instance ) {
			self::$instance = new EnumType(
				array(
					'name'        => 'Color',
					'description' => __( 'A simple color palette', 'poocommerce' ),
					'values'      => array(
						'RED'   => array(
							'value'       => ColorEnum::Red,
							'description' => __( 'Red', 'poocommerce' ),
						),
						'GREEN' => array(
							'value'       => ColorEnum::Green,
							'description' => __( 'Green', 'poocommerce' ),
						),
						'BLUE'  => array(
							'value' => ColorEnum::Blue,
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
