<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Enums;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Enums\Priority as PriorityEnum;
use Automattic\PooCommerce\Api\Infrastructure\Schema\EnumType;

class Priority {
	private static ?EnumType $instance = null;

	public static function get(): EnumType {
		if ( null === self::$instance ) {
			self::$instance = new EnumType(
				array(
					'name'        => 'TaskPriority',
					'description' => __( 'Priority level for a task', 'poocommerce' ),
					'values'      => array(
						'LOW'             => array(
							'value'       => PriorityEnum::Low,
							'description' => __( 'Low priority', 'poocommerce' ),
						),
						'NORMAL_PRIORITY' => array(
							'value' => PriorityEnum::Normal,
						),
						'HIGH'            => array(
							'value'             => PriorityEnum::High,
							'description'       => __( 'High priority', 'poocommerce' ),
							'deprecationReason' => 'Use NORMAL_PRIORITY instead.',
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
