blank_issues_enabled: true
contact_links:
  - name: Feature Requests
    url: https://poocommerce.com/feature-requests/poocommerce/
    about: If you have an idea for a new feature that you wished existed in PooCommerce, take a look at our Feature Requests and vote, or open a new Feature Request yourself!
  - name: 🔒 Security issue
    url: https://hackerone.com/automattic/
    about: For security reasons, please report all security issues via HackerOne. If the issue is valid, a bug bounty will be paid out to you. Please disclose responsibly and not via GitHub (which allows for exploiting issues in the wild before the patch is released).
  - name: ❓ Support Question
    url: https://poocommerce.com/document/poocommerce-self-service-guide/
    about: If you have a question please see our docs or use our forums, helpdesk, or Slack community!
