<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class DeleteCouponResult {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'DeleteCouponResult',
					'description' => __( 'The result of deleting a coupon.', 'poocommerce' ),
					'fields'      => fn() => array(
						'id'      => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The ID of the deleted coupon.', 'poocommerce' ),
						),
						'deleted' => array(
							'type'        => Type::nonNull( Type::boolean() ),
							'description' => __( 'Whether the coupon was permanently deleted.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
