<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\ProductStatus as ProductStatusType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\ProductType as ProductTypeType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\StockStatus as StockStatusType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\ProductDimensions;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\ProductImage;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\ProductAttribute;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Pagination\ProductReviewConnection as ProductReviewConnectionType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Scalars\DateTime as DateTimeType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Interfaces\Product as ProductInterface;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class ExternalProduct {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'ExternalProduct',
					'description' => __( 'An external/affiliate product.', 'poocommerce' ),
					'interfaces'  => fn() => array(
						ProductInterface::get(),
					),
					'fields'      => fn() => array(
						'product_url'       => array(
							'type'        => Type::string(),
							'description' => __( 'The external product URL.', 'poocommerce' ),
						),
						'button_text'       => array(
							'type'        => Type::string(),
							'description' => __( 'The text for the external product button.', 'poocommerce' ),
						),
						'name'              => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The product name.', 'poocommerce' ),
						),
						'slug'              => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The product slug.', 'poocommerce' ),
						),
						'sku'               => array(
							'type'        => Type::string(),
							'description' => __( 'The product SKU.', 'poocommerce' ),
						),
						'description'       => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The full product description.', 'poocommerce' ),
						),
						'short_description' => array(
							'type'              => Type::nonNull( Type::string() ),
							'description'       => __( 'The short product description.', 'poocommerce' ),
							'deprecationReason' => 'Use description instead.',
						),
						'status'            => array(
							'type'        => Type::nonNull( ProductStatusType::get() ),
							'description' => __( 'The product status.', 'poocommerce' ),
						),
						'raw_status'        => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The raw status as stored in WordPress. Useful when status is OTHER (e.g. plugin-added post statuses).', 'poocommerce' ),
						),
						'product_type'      => array(
							'type'        => Type::nonNull( ProductTypeType::get() ),
							'description' => __( 'The product type.', 'poocommerce' ),
						),
						'raw_product_type'  => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The raw product type as stored in PooCommerce. Useful when product_type is OTHER (e.g. plugin-added types like subscription, bundle).', 'poocommerce' ),
						),
						'regular_price'     => array(
							'type'        => Type::string(),
							'description' => __( 'The regular price of the product. Null when not set.', 'poocommerce' ),
							'args'        => array(
								'formatted' => array(
									'type'         => Type::boolean(),
									'defaultValue' => true,
									'description'  => __( 'Whether to apply currency formatting.', 'poocommerce' ),
								),
							),
						),
						'sale_price'        => array(
							'type'        => Type::string(),
							'description' => __( 'The sale price of the product.', 'poocommerce' ),
							'args'        => array(
								'formatted' => array(
									'type'         => Type::boolean(),
									'defaultValue' => true,
									'description'  => __( 'When true, returns price with currency symbol.', 'poocommerce' ),
								),
							),
						),
						'stock_status'      => array(
							'type'        => Type::nonNull( StockStatusType::get() ),
							'description' => __( 'The stock status of the product.', 'poocommerce' ),
						),
						'raw_stock_status'  => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The raw stock status as stored in PooCommerce. Useful when stock_status is OTHER (e.g. plugin-added statuses).', 'poocommerce' ),
						),
						'stock_quantity'    => array(
							'type'        => Type::int(),
							'description' => __( 'The number of items in stock.', 'poocommerce' ),
						),
						'dimensions'        => array(
							'type'        => ProductDimensions::get(),
							'description' => __( 'The product dimensions.', 'poocommerce' ),
						),
						'images'            => array(
							'type'        => Type::nonNull( Type::listOf( Type::nonNull( ProductImage::get() ) ) ),
							'description' => __( 'The product images.', 'poocommerce' ),
						),
						'attributes'        => array(
							'type'        => Type::nonNull( Type::listOf( Type::nonNull( ProductAttribute::get() ) ) ),
							'description' => __( 'The product attributes.', 'poocommerce' ),
						),
						'reviews'           => array(
							'type'        => Type::nonNull( ProductReviewConnectionType::get() ),
							'description' => __( 'Customer reviews for this product.', 'poocommerce' ),
						),
						'date_created'      => array(
							'type'        => DateTimeType::get(),
							'description' => __( 'The date the product was created.', 'poocommerce' ),
						),
						'date_modified'     => array(
							'type'        => DateTimeType::get(),
							'description' => __( 'The date the product was last modified.', 'poocommerce' ),
						),
						'id'                => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The unique numeric identifier.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
