<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class ProductImage {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'ProductImage',
					'description' => __( 'Represents a product image.', 'poocommerce' ),
					'fields'      => fn() => array(
						'id'       => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The image attachment ID.', 'poocommerce' ),
						),
						'url'      => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The image URL.', 'poocommerce' ),
						),
						'alt'      => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The image alt text.', 'poocommerce' ),
						),
						'position' => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The image display position.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
