<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class ProductDimensions {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'ProductDimensions',
					'description' => __( 'Physical dimensions and weight of a product.', 'poocommerce' ),
					'fields'      => fn() => array(
						'length' => array(
							'type'        => Type::float(),
							'description' => __( 'The product length.', 'poocommerce' ),
						),
						'width'  => array(
							'type'        => Type::float(),
							'description' => __( 'The product width.', 'poocommerce' ),
						),
						'height' => array(
							'type'        => Type::float(),
							'description' => __( 'The product height.', 'poocommerce' ),
						),
						'weight' => array(
							'type'        => Type::float(),
							'description' => __( 'The product weight.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
