<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class ProductAttribute {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'ProductAttribute',
					'description' => __( 'A product attribute.', 'poocommerce' ),
					'fields'      => fn() => array(
						'name'        => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The attribute display name.', 'poocommerce' ),
						),
						'slug'        => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The attribute taxonomy or key name.', 'poocommerce' ),
						),
						'options'     => array(
							'type'        => Type::nonNull( Type::listOf( Type::nonNull( Type::string() ) ) ),
							'description' => __( 'The available attribute values.', 'poocommerce' ),
						),
						'position'    => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The display order position.', 'poocommerce' ),
						),
						'visible'     => array(
							'type'        => Type::nonNull( Type::boolean() ),
							'description' => __( 'Whether the attribute is visible on the product page.', 'poocommerce' ),
						),
						'variation'   => array(
							'type'        => Type::nonNull( Type::boolean() ),
							'description' => __( 'Whether the attribute is used for variations.', 'poocommerce' ),
						),
						'is_taxonomy' => array(
							'type'        => Type::nonNull( Type::boolean() ),
							'description' => __( 'Whether the attribute is a global taxonomy attribute.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
