<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Scalars\DateTime as DateTimeType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class ProductReview {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'ProductReview',
					'description' => __( 'Represents a customer review for a product.', 'poocommerce' ),
					'fields'      => fn() => array(
						'id'           => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The review ID.', 'poocommerce' ),
						),
						'product_id'   => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The product ID this review belongs to.', 'poocommerce' ),
						),
						'reviewer'     => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The reviewer name.', 'poocommerce' ),
						),
						'review'       => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The review content.', 'poocommerce' ),
						),
						'rating'       => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The review rating (1-5).', 'poocommerce' ),
						),
						'date_created' => array(
							'type'        => DateTimeType::get(),
							'description' => __( 'The date the review was created.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
