<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class SelectedAttribute {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'SelectedAttribute',
					'description' => __( 'A selected attribute value on a product variation.', 'poocommerce' ),
					'fields'      => fn() => array(
						'name'  => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The attribute name or slug.', 'poocommerce' ),
						),
						'value' => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The selected attribute value.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
