<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Interfaces;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\WidgetReview as WidgetReviewType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\InterfaceType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class Identifiable {
	private static ?InterfaceType $instance = null;

	public static function get(): InterfaceType {
		if ( null === self::$instance ) {
			self::$instance = new InterfaceType(
				array(
					'name'        => 'HasId',
					'description' => __( 'An object with a numeric identifier', 'poocommerce' ),
					'fields'      => fn() => array(
						'id' => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The unique numeric identifier', 'poocommerce' ),
						),
					),
					'resolveType' => function ( $value ) {
						$class = get_class( $value );
						$map = array(
							'Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Types\WidgetReview' => WidgetReviewType::get(),
						);
						return $map[ $class ] ?? null;
					},
				)
			);
		}
		return self::$instance;
	}
}
