<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Interfaces;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\Gadget as GadgetType;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\Widget as WidgetType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\InterfaceType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class Named {
	private static ?InterfaceType $instance = null;

	public static function get(): InterfaceType {
		if ( null === self::$instance ) {
			self::$instance = new InterfaceType(
				array(
					'name'        => 'Named',
					'description' => __( 'An object with a human-readable label', 'poocommerce' ),
					'fields'      => fn() => array(
						'label' => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The display label for this object', 'poocommerce' ),
						),
						'id'    => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The unique numeric identifier', 'poocommerce' ),
						),
					),
					'resolveType' => function ( $value ) {
						$class = get_class( $value );
						$map = array(
							'Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Types\Gadget' => GadgetType::get(),
							'Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Types\Widget' => WidgetType::get(),
						);
						return $map[ $class ] ?? null;
					},
				)
			);
		}
		return self::$instance;
	}
}
