<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated;

use Automattic\PooCommerce\Api\Infrastructure\Schema\Schema;

class GraphQLController extends \Automattic\PooCommerce\Api\Infrastructure\GraphQLControllerBase {
	protected function build_schema(): Schema {
		return new Schema(
			array(
				'query'    => RootQueryType::get(),
				'mutation' => RootMutationType::get(),
				'types'    => TypeRegistry::get_interface_implementors(),
			)
		);
	}

	protected function get_class_resolver_fqcn(): ?string {
		return \Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Infrastructure\ClassResolver::class;
	}
}
