<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLMutations\Increment;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLMutations\CreateWidget;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLMutations\PublicCreateWidget;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLMutations\DeleteWidget;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;

class RootMutationType {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'   => 'Mutation',
					'fields' => fn() => array(
						'increment'          => Increment::get_field_definition(),
						'createWidget'       => CreateWidget::get_field_definition(),
						'publicCreateWidget' => PublicCreateWidget::get_field_definition(),
						'deleteWidget'       => DeleteWidget::get_field_definition(),
					),
				)
			);
		}
		return self::$instance;
	}
}
