<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\Gadget;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\Widget;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\WidgetReview;

class TypeRegistry {
	/**
	 * Return all concrete types that implement interfaces.
	 *
	 * Pass this to the Schema 'types' config so that inline fragments
	 * (e.g. `... on VariableProduct`) are resolvable.
	 *
	 * @return array
	 */
	public static function get_interface_implementors(): array {
		return array(
			Gadget::get(),
			Widget::get(),
			WidgetReview::get(),
		);
	}
}
