<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Scalars;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApi\Scalars\DummyDateTime as DummyDateTimeScalar;
use Automattic\PooCommerce\Api\Infrastructure\Schema\CustomScalarType;

class DummyDateTime {
	private static ?CustomScalarType $instance = null;

	public static function get(): CustomScalarType {
		if ( null === self::$instance ) {
			self::$instance = new CustomScalarType(
				array(
					'name'         => 'DummyDateTime',
					'description'  => __( 'An ISO 8601 encoded date/time string used by the dummy API', 'poocommerce' ),
					'serialize'    => fn( $value ) => DummyDateTimeScalar::serialize( $value ),
					'parseValue'   => function ( $value ) {
						try {
							return DummyDateTimeScalar::parse( $value );
						} catch ( \InvalidArgumentException $e ) {
							throw new \Automattic\PooCommerce\Api\Infrastructure\Schema\Error( $e->getMessage() );
						}
					},
					'parseLiteral' => function ( $value_node, ?array $variables = null ) {
						if ( $value_node instanceof \Automattic\PooCommerce\Api\Infrastructure\Schema\AST\StringValueNode ) {
							try {
								return DummyDateTimeScalar::parse( $value_node->value );
							} catch ( \InvalidArgumentException $e ) {
								throw new \Automattic\PooCommerce\Api\Infrastructure\Schema\Error( $e->getMessage() );
							}
						}
						throw new \Automattic\PooCommerce\Api\Infrastructure\Schema\Error(
							'DummyDateTime must be a string, got: ' . $value_node->kind
						);
					},
				)
			);
		}
		return self::$instance;
	}
}
