<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Input;

use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\DiscountType as DiscountTypeType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\CouponStatus as CouponStatusType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\InputObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class CreateCoupon {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if ( null === self::$instance ) {
			self::$instance = new InputObjectType(
				array(
					'name'        => 'CreateCouponInput',
					'description' => __( 'Data required to create a new coupon.', 'poocommerce' ),
					'fields'      => fn() => array(
						'code'                        => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The coupon code.', 'poocommerce' ),
						),
						'description'                 => array(
							'type'        => Type::string(),
							'description' => __( 'The coupon description.', 'poocommerce' ),
						),
						'discount_type'               => array(
							'type'        => DiscountTypeType::get(),
							'description' => __( 'The type of discount.', 'poocommerce' ),
						),
						'amount'                      => array(
							'type'        => Type::float(),
							'description' => __( 'The discount amount.', 'poocommerce' ),
						),
						'status'                      => array(
							'type'        => CouponStatusType::get(),
							'description' => __( 'The coupon status.', 'poocommerce' ),
						),
						'date_expires'                => array(
							'type'        => Type::string(),
							'description' => __( 'The date the coupon expires (ISO 8601).', 'poocommerce' ),
						),
						'individual_use'              => array(
							'type'        => Type::boolean(),
							'description' => __( 'Whether the coupon can only be used alone.', 'poocommerce' ),
						),
						'product_ids'                 => array(
							'type'        => Type::listOf( Type::nonNull( Type::int() ) ),
							'description' => __( 'Product IDs the coupon can be applied to.', 'poocommerce' ),
						),
						'excluded_product_ids'        => array(
							'type'        => Type::listOf( Type::nonNull( Type::int() ) ),
							'description' => __( 'Product IDs excluded from the coupon.', 'poocommerce' ),
						),
						'usage_limit'                 => array(
							'type'        => Type::int(),
							'description' => __( 'Maximum number of times the coupon can be used in total.', 'poocommerce' ),
						),
						'usage_limit_per_user'        => array(
							'type'        => Type::int(),
							'description' => __( 'Maximum number of times the coupon can be used per customer.', 'poocommerce' ),
						),
						'limit_usage_to_x_items'      => array(
							'type'        => Type::int(),
							'description' => __( 'Maximum number of items the coupon can be applied to.', 'poocommerce' ),
						),
						'free_shipping'               => array(
							'type'        => Type::boolean(),
							'description' => __( 'Whether the coupon grants free shipping.', 'poocommerce' ),
						),
						'product_categories'          => array(
							'type'        => Type::listOf( Type::nonNull( Type::int() ) ),
							'description' => __( 'Product category IDs the coupon applies to.', 'poocommerce' ),
						),
						'excluded_product_categories' => array(
							'type'        => Type::listOf( Type::nonNull( Type::int() ) ),
							'description' => __( 'Product category IDs excluded from the coupon.', 'poocommerce' ),
						),
						'exclude_sale_items'          => array(
							'type'        => Type::boolean(),
							'description' => __( 'Whether the coupon excludes items on sale.', 'poocommerce' ),
						),
						'minimum_amount'              => array(
							'type'        => Type::float(),
							'description' => __( 'Minimum order amount required to use the coupon.', 'poocommerce' ),
						),
						'maximum_amount'              => array(
							'type'        => Type::float(),
							'description' => __( 'Maximum order amount allowed to use the coupon.', 'poocommerce' ),
						),
						'email_restrictions'          => array(
							'type'        => Type::listOf( Type::nonNull( Type::string() ) ),
							'description' => __( 'Email addresses that can use this coupon.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
