<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Input;

use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\ProductStatus as ProductStatusType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\ProductType as ProductTypeType;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Input\Dimensions as DimensionsInput;
use Automattic\PooCommerce\Api\Infrastructure\Schema\InputObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class UpdateProduct {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if ( null === self::$instance ) {
			self::$instance = new InputObjectType(
				array(
					'name'        => 'UpdateProductInput',
					'description' => __( 'Data for updating an existing product.', 'poocommerce' ),
					'fields'      => fn() => array(
						'id'                => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The ID of the product to update.', 'poocommerce' ),
						),
						'name'              => array(
							'type'        => Type::string(),
							'description' => __( 'The product name.', 'poocommerce' ),
						),
						'slug'              => array(
							'type'        => Type::string(),
							'description' => __( 'The product slug.', 'poocommerce' ),
						),
						'sku'               => array(
							'type'        => Type::string(),
							'description' => __( 'The product SKU.', 'poocommerce' ),
						),
						'description'       => array(
							'type'        => Type::string(),
							'description' => __( 'The full product description.', 'poocommerce' ),
						),
						'short_description' => array(
							'type'        => Type::string(),
							'description' => __( 'The short product description.', 'poocommerce' ),
						),
						'status'            => array(
							'type'        => ProductStatusType::get(),
							'description' => __( 'The product status.', 'poocommerce' ),
						),
						'product_type'      => array(
							'type'        => ProductTypeType::get(),
							'description' => __( 'The product type.', 'poocommerce' ),
						),
						'regular_price'     => array(
							'type'        => Type::float(),
							'description' => __( 'The regular price.', 'poocommerce' ),
						),
						'sale_price'        => array(
							'type'        => Type::float(),
							'description' => __( 'The sale price.', 'poocommerce' ),
						),
						'manage_stock'      => array(
							'type'        => Type::boolean(),
							'description' => __( 'Whether to manage stock.', 'poocommerce' ),
						),
						'stock_quantity'    => array(
							'type'        => Type::int(),
							'description' => __( 'The number of items in stock.', 'poocommerce' ),
						),
						'dimensions'        => array(
							'type'        => DimensionsInput::get(),
							'description' => __( 'The product dimensions.', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
