<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Input;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Enums\Color as ColorType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\InputObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class WidgetFilter {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if ( null === self::$instance ) {
			self::$instance = new InputObjectType(
				array(
					'name'        => 'WidgetFilterArgs',
					'description' => __( 'Filters applied to a widget listing', 'poocommerce' ),
					'fields'      => fn() => array(
						'search' => array(
							'type'        => Type::string(),
							'description' => __( 'A free-text search term', 'poocommerce' ),
						),
						'color'  => array(
							'type'        => ColorType::get(),
							'description' => __( 'Filter widgets by color', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
