<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLQueries;

use Automattic\PooCommerce\Api\Queries\Coupons\GetCoupon as GetCouponCommand;
use Automattic\PooCommerce\Api\Infrastructure\QueryInfoExtractor;
use Automattic\PooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\PooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\Coupon as CouponType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ResolveInfo;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class GetCoupon {
	public static function get_field_definition(): array {
		return array(
			'type'          => CouponType::get(),
			'description'   => __( 'Retrieve a single coupon by ID or code. Exactly one of the two arguments must be provided.', 'poocommerce' ),
			'authorization' => array(
				array(
					'attribute' => 'RequiredCapability',
					'args'      => array(
						0 => 'read_private_shop_coupons',
					),
				),
			),
			'args'          => array(
				'id'   => array(
					'type'         => Type::int(),
					'description'  => __( 'The ID of the coupon to retrieve.', 'poocommerce' ),
					'defaultValue' => null,
				),
				'code' => array(
					'type'         => Type::string(),
					'description'  => __( 'The coupon code to look up.', 'poocommerce' ),
					'defaultValue' => null,
				),
			),
			'resolve'       => array( self::class, 'resolve' ),
		);
	}

	public static function resolve( mixed $root, array $args, mixed $context, ResolveInfo $info ): mixed {
		// Standalone authorization gate: no authorize() method on the command,
		// so the autodiscovered authorization attributes are the sole guard.
		if ( ! self::compute_preauthorized( $context['principal'] ) ) {
			throw ResolverHelpers::build_authorization_error( $context['principal'] );
		}

		// Publish the root query's metadata so downstream field-level
		// authorization gates can read it via `$_metadata['query']`.
		// $context is an ArrayObject (see GraphQLController::process_request())
		// so the mutation propagates to nested resolvers.
		$context['_query_metadata'] = array();

		$command = \Automattic\PooCommerce\Api\Infrastructure\ClassResolver::resolve_class( GetCouponCommand::class );

		$execute_args = array();
		if ( array_key_exists( 'id', $args ) ) {
			$execute_args['id'] = $args['id'];
		}
		if ( array_key_exists( 'code', $args ) ) {
			$execute_args['code'] = $args['code'];
		}

		$result = ResolverHelpers::execute_command( $command, $execute_args );

		return $result;
	}

	/**
	 * Compute the value `_preauthorized` would carry for a given principal —
	 * the AND of the autodiscovered authorization attributes' authorize()
	 * outcomes on this command. Single source of truth for both the resolver's
	 * own gates and external (code-API) callers asking about authorization
	 * without going through GraphQL execution.
	 *
	 * Returns true vacuously when the command has no authorization attributes
	 * (in that case authorize() on the command is the sole guard, and that
	 * method should be consulted instead).
	 */
	public static function compute_preauthorized( \Automattic\PooCommerce\Api\Infrastructure\Principal $principal ): bool {
		return ( new \Automattic\PooCommerce\Api\Attributes\RequiredCapability( 'read_private_shop_coupons' ) )->authorize( $principal );
	}
}
