<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class OperationResult {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'OperationResult',
					'description' => __( 'The result of a generic operation', 'poocommerce' ),
					'fields'      => fn() => array(
						'success' => array(
							'type'        => Type::nonNull( Type::boolean() ),
							'description' => __( 'Whether the operation succeeded', 'poocommerce' ),
						),
						'message' => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'A human-readable status message', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
