<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Enums\Color as ColorType;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Enums\Priority as PriorityType;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\WidgetReview;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Pagination\WidgetReviewConnection as WidgetReviewConnectionType;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Scalars\DummyDateTime as DummyDateTimeType;
use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Interfaces\Named as NamedInterface;
use Automattic\PooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class Widget {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'Widget',
					'description' => __( 'A dummy widget that exercises every output-type attribute', 'poocommerce' ),
					'interfaces'  => fn() => array(
						NamedInterface::get(),
					),
					'fields'      => fn() => array(
						'slug'             => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'A short slug', 'poocommerce' ),
						),
						'caption'          => array(
							'type'          => Type::string(),
							'description'   => __( 'An optional caption', 'poocommerce' ),
							'metadata'      => array(
								'visible_sample' => 'visible',
							),
							'authorization' => array(
								array(
									'attribute' => 'RequiredCapability',
									'args'      => array(
										0 => 'manage_poocommerce',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
								$principal = $context['principal'];
								$_metadata = array(
									'query' => $context['_query_metadata'] ?? array(),
									'type'  => array(),
									'field' => array(
										'visible_sample' => 'visible',
									),
								);
								$_args     = $args;
								$_parent   = $parent;
								if ( ! ( ( new \Automattic\PooCommerce\Api\Attributes\RequiredCapability( 'manage_poocommerce' ) )->authorize( $principal ) ) ) {
									throw ResolverHelpers::build_field_authorization_error( $principal, 'Widget', 'caption', 'RequiredCapability' );
								}
																return $parent->caption;
							},
						),
						'color'            => array(
							'type'        => Type::nonNull( ColorType::get() ),
							'description' => __( 'The widget color', 'poocommerce' ),
						),
						'priority'         => array(
							'type'        => Type::nonNull( PriorityType::get() ),
							'description' => __( 'Priority assigned to this widget', 'poocommerce' ),
						),
						'tag_ids'          => array(
							'type'        => Type::nonNull( Type::listOf( Type::nonNull( Type::int() ) ) ),
							'description' => __( 'Tag IDs assigned to this widget', 'poocommerce' ),
						),
						'featured_reviews' => array(
							'type'        => Type::nonNull( Type::listOf( Type::nonNull( WidgetReview::get() ) ) ),
							'description' => __( 'Notable comments left on this widget', 'poocommerce' ),
						),
						'reviews'          => array(
							'type'        => Type::nonNull( WidgetReviewConnectionType::get() ),
							'description' => __( 'Reviews of the widget', 'poocommerce' ),
						),
						'date_created'     => array(
							'type'        => DummyDateTimeType::get(),
							'description' => __( 'When the widget was created', 'poocommerce' ),
						),
						'price'            => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The widget price', 'poocommerce' ),
							'args'        => array(
								'formatted' => array(
									'type'         => Type::boolean(),
									'defaultValue' => false,
									'description'  => __( 'When true, prepend a $ sign', 'poocommerce' ),
								),
							),
						),
						'legacy_price'     => array(
							'type'              => Type::nonNull( Type::string() ),
							'description'       => __( 'A field flagged for removal', 'poocommerce' ),
							'deprecationReason' => 'Use price instead.',
						),
						'label'            => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The display label for this object', 'poocommerce' ),
						),
						'id'               => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The unique numeric identifier', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
