<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Interfaces\Identifiable as IdentifiableInterface;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class WidgetReview {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'WidgetReview',
					'description' => __( 'A review left for a widget', 'poocommerce' ),
					'interfaces'  => fn() => array(
						IdentifiableInterface::get(),
					),
					'fields'      => fn() => array(
						'body'  => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'The body of the review', 'poocommerce' ),
						),
						'score' => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'A score between 0 and 5', 'poocommerce' ),
						),
						'id'    => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'The unique numeric identifier', 'poocommerce' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
