<?php

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Pagination;

use Automattic\PooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLTypes\Output\Widget as WidgetType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\PooCommerce\Api\Infrastructure\Schema\Type;

class WidgetConnection {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'WidgetConnection',
					'description' => __( 'A connection to a list of Widget items.', 'poocommerce' ),
					'fields'      => fn() => array(
						'edges'       => array(
							'type' => Type::nonNull(
								Type::listOf(
									Type::nonNull(
										WidgetEdge::get()
									)
								)
							),
						),
						'nodes'       => array(
							'type' => Type::nonNull(
								Type::listOf(
									Type::nonNull(
										WidgetType::get()
									)
								)
							),
						),
						'page_info'   => array(
							'type' => Type::nonNull( PageInfo::get() ),
						),
						'total_count' => array(
							'type' => Type::nonNull( Type::int() ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
